### ISSUE TITLE
Hands2017数据集下载

### ISSUE THREAD

**Issue by HQXing-11** [dejianwei/HigherA2J#1]
你好 请问一下，我在官方网站上下载Hands2017训练集的压缩文件后，解压时显示文件损坏。这是什么问题呀

**Comment by dejianwei** [comment]
不好意思这么晚回复，我也不确定什么原因，我之前应该没这个问题，要不重新下载一次试试吧

**Comment by HQXing-11** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by HQXing-11** [comment]
> 不好意思这么晚回复，我也不确定什么原因，我之前应该没这个问题，要不重新下载一次试试吧

谢谢你呀，我已经解压好了
